### ISSUE TITLE
The links in the PDF are broken

### ISSUE THREAD

**Issue by gschizas** [jamhamster/TZX-Cassette-Mod#1]
All the links in the BOM in the PDF point to empty pages, because instead of having the full URL, they point to a shortened URL, e.g. instead of `https://www.amazon.co.uk/TUOFENG-Electrical-Flexible-Different-Electronics/dp/B07G712DY4/`, they point to `https://www.amazon.co.uk/TUOFENG-Elec...` (obviously an artefact of copy-pasting from YouTube's description.

**Comment by jamhamster** [comment]
Hi, I have updated the document with the V2 of the Cassette and have checked the links.
