### ISSUE TITLE
Could be valid for Amstrad CPC?

### ISSUE THREAD

**Issue by jagonga** [jamhamster/TZX-Cassette-Mod#2]
Hello,
It is a very good project.
I would like to know if loading an Amstrad game into SD, could be valid also for this device.
Many thanks.

Kind regards,
Javier

**Comment by jamhamster** [comment]
It could and would work well in most cases but there is a problem with games that pause the cassette deck. the software will not know that a pause has been done so these games will fail. Something could be done in software to fix this but the project is still in its infancy. Try your CPC with a TZXDuino and an in car cassette adapter, if that works for you then this will too. :-)
